apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: do-spaces-credentials
  namespace: flux-system
spec:
  encryptedData:
    access_key_id: AgA6anop2YWKQ4xmLuLMpmc/sOZ7R+J+SKPmXXUruaRZmyELXjLWBBR95CJPEoNRfpRNwe+o7uUbiNcj7hjODoM4qAmqnfpUK21LKWnqO/aBgGDR0Csy+1dNn2fZOpfIh4/6b52sPLjAolFmt9yqhgC3xjo3dNp6Rrkm+MfXyWqzNxDaLSxbZcPH8azEVPl3naHjPKJONgHzLrNFTP7nTK+KD/YDnOVBmaZuRyg+fTIM1teB8Ga8Y66je4O+8KnnbhQ+4emz2OrPnpOQHRxDa3oE9CtRsBx/nMKO8ABiG9wmNz1BpH+dmPae80ej1w2bfF7gfwYBl1OFjuHal5GEqrZ+nQ1ZQXR7hloxwTEekudxPs/IWdB7VU8XlA7OFtD6k5gg2OYuXUD4u2obZa3mGtxN8EMvlyyTQ0III7UW18ZkM0hlOevNgAXEpWzT/+jeAhtNuoIgfhAtGaXuRiOq5hhE9Q1fZ8FQqTENk7qKjmjcaLKfSy2Gz2vyR+3EVtxcZjFqmBpJnBnZQgFy53oQgwmRerT288dsT5FfJRDos44ivURl/NhxIFwQgTg09mWc9hhI9c1gGCncU6Nw524pwjm7SOrAtCCg2/DhyvebP3ZDro+ufjk2wKgLx6aQ9h+yln4VwSJA3Tz4GA8SF0xSnZa5UL3rTFx1NmKq3+KPAN39C0ocAhAQ5N1XvKQispFXN7QiRRLHFiz4gLnaBeBfVuYnAdCBsw==
    secret_access_key: AgBJKdwSAfptEq7mcr4UbZ8w7rfl1tvROa3w5vH1Aggdx/DbraMpPdPoIGcZ2t5s8CRXltPaESYCgrTxG1PBtGIRPphqepQESusX8FRwUI3Y/eS2dycCg3tRdLIwbW8PTMdJDLgqGJpQxdrSyj6Z9AciTzA0JiWow60Ex6H/mwu94Zg720krc/hJ0EEFSJ6AKIkxTkj/n8OyovqSIVkX+krcCHYDvHYS98sKSNkEJJKslJgNJqv/Z7HTVBgq5hNZIjdohWQT3IHLiGcJIf7N9aFUS41gxCF6BUDsivA3W3owaZg2Jzwy0c9UtBxfcEIAgld4h579a5f8iKSSw199hYvtOd31AjMQ66PAnW3Nt33fP1dvjX2xOCQIH/TKsAFHsszMj9ZNjk3YaSl3unp+U6v5BWpZKJDF47KMMDYAmlIi7qg/3quc8gyYCTQg+TGZ8pfEBPvOEW9iKagERl83JJdhD+62uS3Iir2PhXUGGfp8cp2ZR/XokR/E8//h5WL/C5haDXvD8u5mKy9Ad+W1XR4xea0ZTcJHP+Jio+ZzJLgINdFjPPeoQWn94jpP/nurHUHrZ2QVO+YdsAxBGu2+TrPOd5njAvepgSBxFJED15ohPgE9GEKZdv1hr6XSbd0QzQmXnCLj7r+K76KYm9E5savl7vseNVfVi3VXjlXUwVe+LeXYuz6Y2kXBHZDrqZh0WVthQeE6jyQ7SRAE0PtfE6v3h1waKOBewi8BSjrj4Y/jQIRT2HYIaRiKfKqD
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: do-spaces-credentials
      namespace: flux-system

