---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  namespace: flux-system
  name: ambassador-certificate-infrastructure
spec:
  interval: 1m0s
  prune: true
  path: "ambassador-certificate-infrastructure"
  sourceRef:
    kind: GitRepository
    name: github

