---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  namespace: flux-system
  name: argocd
spec:
  interval: 1m0s
  prune: true
  path: "argocd/infrastructure"
  sourceRef:
    kind: GitRepository
    name: github

