apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: otogone.be
  # Cert-Manager will put the resulting Secret in the same Kubernetes namespace as the Certificate.
  namespace: ambassador
spec:
  # Secret name to create, where the private key and certificate should be stored.
  secretName: otogone.be
  # What Issuer to use for getting the certificate.
  issuerRef:
    name: letsencrypt-dev-wcard
    kind: Issuer
    group: cert-manager.io
  # Common name to be used on the Certificate.
  commonName: "*.otogone.be"
  # List of DNS subjectAltNames to be set on the Certificate.
  dnsNames:
    - "otogone.be"
    - "*.otogone.be"
