---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: github
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://github.com/fransguelinckx/digitalocean-k8s-challenge
  ref:
    branch: main
